services:
  pgsql:
    image: postgres:15
    container_name: planx_db
    environment:
      POSTGRES_DB: planx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - planx_pgdata:/var/lib/postgresql/data

volumes:
  planx_pgdata: